// Generated by CoffeeScript 1.8.0
(function() {
  var app, express, fs, json, jsonp, logRequest, port, server;

  express = require('express');

  fs = require('fs');

  app = express();

  port = process.env.PORT || 4000;

  json = fs.readFileSync('./src/nav.json', 'utf8');

  jsonp = "render(" + json + ");";

  logRequest = function(url, status) {
    return console.log('Request for: ' + url + ' (' + status + ')');
  };

  app.get('/', function(req, res) {
    logRequest(req.url, res.statusCode);
    return res.redirect(301, 'https://github.com/mmwtsn/markup-api#markup-api');
  });

  app.get('/api/v1/cloud.json', function(req, res) {
    logRequest(req.url, res.statusCode);
    res.header('Content-Type', 'application/json');
    res.header('Charset', 'utf-8');
    if (req.query.hasOwnProperty('callback')) {
      return res.send(jsonp);
    } else {
      return res.send(json);
    }
  });

  server = app.listen(port, function() {
    return console.log('Listening on port %d', server.address().port);
  });

}).call(this);
